apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-mysql
spec:
  ports:
  - port: {{ .Values.mysqlStatic.port }}
    targetPort: {{ .Values.mysqlStatic.port }}
  selector:
    app: {{ include "todo-app.fullname" . }}-mysql