apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysqlStatic.rootPassword | quote }}
  mysql-password: {{ .Values.mysqlStatic.password | quote }}
  mysql-user: {{ .Values.mysqlStatic.user | quote }}
  mysql-database: {{ .Values.mysqlStatic.database | quote }}
  database-url: {{ .Values.databaseUrl | quote }}