apiVersion: apps/v1
# default kind is deployment if gotmpl not provide kind
kind: {{ .Values.mysql.kind | default "Deployment" }}
metadata:
  name: {{ include "todo-app.fullname" . }}-mysql
spec:
  # if is Statefule set then must have serviceName
  {{- if eq (.Values.mysql.kind | default "Deployment") "StatefulSet" }}
  serviceName: {{ include "todo-app.fullname" . }}-mysql
  {{- end }}
  # defalut replica is 1
  replicas: {{ .Values.mysql.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "todo-app.fullname" . }}-mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        args:
        - --default-authentication-plugin=mysql_native_password
        ports:
        - containerPort: {{ .Values.mysqlStatic.port }}
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-app.fullname" . }}-mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-app.fullname" . }}-mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-app.fullname" . }}-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-app.fullname" . }}-mysql-secret
              key: mysql-password
        # Strict alignment: Use nindent 10 to ensure perfect integration into containers scope
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        
        - name: mysql-init-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        {{- if .Values.mysql.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "todo-app.fullname" . }}-mysql-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      
      - name: mysql-init-volume
        configMap:
          name: {{ include "todo-app.fullname" . }}-mysql-init-script

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-mysql-init-script
data:
  
  init.sql: |
    
    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '{{ .Values.mysqlStatic.rootPassword }}';
    
    ALTER USER '{{ .Values.mysqlStatic.user }}'@'%' IDENTIFIED WITH mysql_native_password BY '{{ .Values.mysqlStatic.password }}';
    
    FLUSH PRIVILEGES;