apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd    
spec:
  project: default
  source:
    repoURL: https://github.com/pengchao2022/python_flask_app_cd
    targetRevision: main
    path: manifests 
    
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true # perform full matching and synchronization
      selfHeal: true # automatically fix wrong configration
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # to solve resource conflicts

