environments:
  default:
    values:
      - global:
          environment: production

# Use three horizontal lines to separate the environment and the release
---

releases:
  - name: todo-app
    chart: .
    namespace: todo-app
    values:
      - ./helm.gotmpl