environments:
  default:
    values:
      - global:
          environment: production

# 用三个横杠劈开环境与发布
---

releases:
  - name: todo-app
    chart: .
    namespace: todo-app
    values:
      - ./helm.gotmpl