# 全局配置
global:
  environment: production  # production, staging, development

# 应用配置
replicaCount: 1

image:
  repository: pengchaoma/flask-todo-app
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# MySQL 配置
mysql:
  enabled: true
  image: mysql:8.4
  database: todo_db
  user: todo_user
  password: "StrongPassword123"
  rootPassword: "RootPassword123"
  persistence:
    enabled: true
    size: 5Gi
    accessModes:
      - ReadWriteOnce
    storageClass: ""
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    port: 3306